### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by Lowkik-Sai** [vladdenisov/crove-bot#15]
I copy your purge command code,
My bot prefix is +
While running +purge 3 or +purge 10 or something : bot is only deleting one message and sending deleteing only one message

**Comment by vladdenisov** [comment]
This command may not work if your messages are more then 14 days old. 

And it should send only one message about deleting.

I'll do more research, but everything worked for me.

**Comment by Lowkik-Sai** [comment]
Messages are fresh!not older
Today messages are also not deleted!
Bot is not able to catch the number
Please help me to bot catch the number and delete Messages
