### ISSUE TITLE
valid intents must be provided for the Client.

### ISSUE THREAD

**Issue by DancingPotatoes** [vladdenisov/crove-bot#18]
when running the bot
It gives me this error
throw new TypeError('CLIENT_MISSING_INTENTS');
^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.

**Comment by vladdenisov** [comment]
This was unbelievably stupid mistake by me. Now it should be fixed. Please, make sure you filled in all parameters in `config.json`!

**Comment by DancingPotatoes** [comment]
cant i delete watson?

**Comment by DancingPotatoes** [comment]
do you mean that i need to install the new patch or no? because i am using the one without lavalink

**Comment by DancingPotatoes** [comment]
nvm i did it but now i have a new problem

SyntaxError: Unexpected token < in JSON at position 0

**Comment by DancingPotatoes** [comment]
at JSON.parse (<anonymous>)
    at C:\Users\good\Desktop\crove-bot-0\node_modules\ytsr\lib\main.js:30:27
    at IncomingMessage.<anonymous> (C:\Users\good\Desktop\crove-bot-0\node_modules\ytsr\lib\util.js:249:7)

**Comment by vladdenisov** [comment]
I haven't tested it yet without lavalink. I'll do it soon

**Comment by DancingPotatoes** [comment]
Okay

**Comment by vladdenisov** [comment]
https://github.com/vladdenisov/crove-bot/tree/ytdl/

This branch should work now
