### ISSUE TITLE
New guild join have problem

### ISSUE THREAD

**Issue by SploeCyber** [vladdenisov/crove-bot#6]
(node:27024) UnhandledPromiseRejectionWarning: TypeError: (intermediate value).setColor(...).setTitle(...).setAuthor(...).setDescription(...).setThumbnail(...).addField(...).addBlankField is not a function

**Comment by vladdenisov** [comment]
Hello. Are you trying to add a bot, that is hosted on my server (I don't have errors in my console)? Or on your own? 
If you are trying to add your own bot, then you need to set it's permissions to `8` (administrator).
The link should look like this 
`https://discordapp.com/oauth2/authorize?&client_id=CLIENT_ID&scope=bot&permissions=8`, 
where `CLIENT_ID` is your client id

**Comment by SploeCyber** [comment]
I have tried to delete .addBlankField. Now it works

**Comment by vladdenisov** [comment]
Strange, but everything works for me. I'll do more tests.
